// Initially generated by #SNMP MIB Compiler Pro 2.1.2.0
// IMPORTANT: This file can be modified, but won't be updated by the compiler again.
// Original file name is C:\Users\lextudio\source\repos\test-field\ip-mib\IP-MIB.mib
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using Lextm.SharpSnmpLib;
using SnmpD;
using Samples.Pipeline;
// using Lextm.SharpSnmpPro.Mib; // TODO: Uncomment if syntax validation is required.

namespace IP_MIB
{
    public sealed class IpNetToMediaCustomRow
    {
        public required int IfIndex { get; set; }
        public required IPAddress Address { get; set; }
        public required byte[] PhysicalAddress { get; set; }
        public required int Type { get; set; }
    }

    partial class ipForwarding
    {
        private ISnmpData _data = new Integer32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IP-MIB", "ipForwarding", value) to validate data
            set { _data = value; }
        }
    }

    partial class ipDefaultTTL
    {
        private ISnmpData _data = new Integer32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IP-MIB", "ipDefaultTTL", value) to validate data
            set { _data = value; }
        }
    }

    partial class ipInReceives
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipInHdrErrors
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipInAddrErrors
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipForwDatagrams
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipInUnknownProtos
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipInDiscards
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipInDelivers
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipOutRequests
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipOutDiscards
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipOutNoRoutes
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipReasmTimeout
    {
        private ISnmpData _data = new Integer32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipReasmReqds
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipReasmOKs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipReasmFails
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipFragOKs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipFragFails
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipFragCreates
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }


    partial class ipAdEntAddr
    {
        public ipAdEntAddr(System.Net.IPAddress address) : this(address.ToString())
        {
            _data = new IP(address);
        }

        private ISnmpData _data = new IP(System.Net.IPAddress.Loopback);

        void OnCreate(string index)
        {
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipAdEntIfIndex
    {
        public ipAdEntIfIndex(System.Net.IPAddress address, int ifIndex) : this(address.ToString())
        {
            _data = new Integer32(ifIndex);
        }

        private ISnmpData _data = new Integer32(0);

        void OnCreate(string index)
        {
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipAdEntNetMask
    {
        public ipAdEntNetMask(System.Net.IPAddress address, System.Net.IPAddress mask) : this(address.ToString())
        {
            _data = new IP(mask);
        }

        private ISnmpData _data = new IP(System.Net.IPAddress.Loopback);

        void OnCreate(string index)
        {
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipAdEntBcastAddr
    {
        public ipAdEntBcastAddr(System.Net.IPAddress address) : this(address.ToString())
        {
            _data = new Integer32(1);
        }

        private ISnmpData _data = new Integer32(0);

        void OnCreate(string index)
        {
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipAdEntReasmMaxSize
    {
        public ipAdEntReasmMaxSize(System.Net.IPAddress address) : this(address.ToString())
        {
            _data = new Integer32(65535);
        }

        private ISnmpData _data = new Integer32(0);

        void OnCreate(string index)
        {
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }


    partial class ipNetToMediaIfIndex
    {
        private readonly IpNetToMediaCustomRow _customRow;

        public ipNetToMediaIfIndex(NetworkInterface ni, params string[] indexes)
            : this(indexes)
        {
            _data = new Integer32(int.Parse(indexes[0]));
        }

        public ipNetToMediaIfIndex(IpNetToMediaCustomRow row)
            : this(row.IfIndex.ToString(), row.Address.ToString())
        {
            _customRow = row;
            _data = new Integer32(row.IfIndex);
        }

        private ISnmpData _data;

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IP-MIB", "ipNetToMediaIfIndex", value) to validate data
            set
            {
                if (_customRow != null && value is Integer32 intValue && intValue.ToInt32() != _customRow.IfIndex)
                {
                    throw new ArgumentException(ErrorCode.InconsistentValue.ToString());
                }

                _data = value;
            }
        }
    }

    partial class ipNetToMediaPhysAddress
    {
        private readonly IpNetToMediaCustomRow _customRow;

        public ipNetToMediaPhysAddress(NetworkInterface ni, params string[] indexes)
            : this(indexes)
        {
            _data = new OctetString(ni.GetPhysicalAddress().GetAddressBytes());
        }

        public ipNetToMediaPhysAddress(IpNetToMediaCustomRow row)
            : this(row.IfIndex.ToString(), row.Address.ToString())
        {
            _customRow = row;
            _data = new OctetString(row.PhysicalAddress);
        }

        private ISnmpData _data;

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IP-MIB", "ipNetToMediaPhysAddress", value) to validate data
            set
            {
                if (_customRow != null && value is OctetString octetString)
                {
                    _customRow.PhysicalAddress = octetString.ToBytes();
                }

                _data = value;
            }
        }
    }

    partial class ipNetToMediaNetAddress
    {
        private readonly IpNetToMediaCustomRow _customRow;

        public ipNetToMediaNetAddress(NetworkInterface ni, params string[] indexes)
            : this(indexes)
        {
            _data = new IP(System.Net.IPAddress.Parse(indexes[1]));
        }

        public ipNetToMediaNetAddress(IpNetToMediaCustomRow row)
            : this(row.IfIndex.ToString(), row.Address.ToString())
        {
            _customRow = row;
            _data = new IP(row.Address);
        }

        private ISnmpData _data = new IP(System.Net.IPAddress.Loopback);

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IP-MIB", "ipNetToMediaNetAddress", value) to validate data
            set
            {
                if (_customRow != null && value is IP ipAddress)
                {
                    var requested = IPAddress.Parse(ipAddress.ToString());
                    if (!requested.Equals(_customRow.Address))
                    {
                        throw new ArgumentException(ErrorCode.InconsistentValue.ToString());
                    }
                }

                _data = value;
            }
        }
    }

    partial class ipNetToMediaType
    {
        private readonly IpNetToMediaCustomRow _customRow;

        public ipNetToMediaType(NetworkInterface ni, params string[] indexes)
            : this(indexes)
        {
            _data = new Integer32(3);
        }

        public ipNetToMediaType(IpNetToMediaCustomRow row)
            : this(row.IfIndex.ToString(), row.Address.ToString())
        {
            _customRow = row;
            _data = new Integer32(row.Type);
        }

        private ISnmpData _data;

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IP-MIB", "ipNetToMediaType", value) to validate data
            set
            {
                if (_customRow != null && value is Integer32 intValue)
                {
                    var numeric = intValue.ToInt32();
                    if (numeric < 1 || numeric > 4)
                    {
                        throw new ArgumentException(ErrorCode.WrongValue.ToString());
                    }

                    _customRow.Type = numeric;
                }

                _data = value;
            }
        }
    }

    partial class ipRoutingDiscards
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInMsgs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInErrors
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInDestUnreachs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInTimeExcds
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInParmProbs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInSrcQuenchs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInRedirects
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInEchos
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInEchoReps
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInTimestamps
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInTimestampReps
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInAddrMasks
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpInAddrMaskReps
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutMsgs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutErrors
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutDestUnreachs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutTimeExcds
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutParmProbs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutSrcQuenchs
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutRedirects
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutEchos
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutEchoReps
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutTimestamps
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutTimestampReps
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutAddrMasks
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class icmpOutAddrMaskReps
    {
        private ISnmpData _data = new Counter32(0);

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { throw new AccessFailureException(); }
        }
    }

    partial class ipAddrTable
    {
        public void OnCreate()
        {
            NetworkChange.NetworkAddressChanged += (sender, args) => LoadElements();
            NetworkChange.NetworkAvailabilityChanged += (sender, args) => LoadElements();
            LoadElements();
        }

        private void LoadElements()
        {
            _elements.Clear();
            int ifIndex = 0;
            foreach (var ni in NetworkInterface.GetAllNetworkInterfaces())
            {
                ifIndex++;
                foreach (var ua in ni.GetIPProperties().UnicastAddresses)
                {
                    if (ua.Address.AddressFamily != System.Net.Sockets.AddressFamily.InterNetwork)
                        continue;

                    var address = ua.Address;
                    var mask = ua.IPv4Mask ?? System.Net.IPAddress.Any;
                    _elements.Add(new ipAdEntAddr(address));
                    _elements.Add(new ipAdEntIfIndex(address, ifIndex));
                    _elements.Add(new ipAdEntNetMask(address, mask));
                    _elements.Add(new ipAdEntBcastAddr(address));
                    _elements.Add(new ipAdEntReasmMaxSize(address));
                }
            }
        }
    }

    partial class ipNetToMediaTable
    {
        private readonly Dictionary<string, IpNetToMediaCustomRow> _customRows = new Dictionary<string, IpNetToMediaCustomRow>(StringComparer.Ordinal);
        private readonly object _syncRoot = new object();

        public void OnCreate()
        {
            NetworkChange.NetworkAddressChanged +=
                (sender, args) => LoadElements();

            NetworkChange.NetworkAvailabilityChanged +=
                (sender, args) => LoadElements();

            LoadElements();
        }

        private void LoadElements()
        {
            lock (_syncRoot)
            {
                _elements.Clear();
                var liveRows = MibHelper.GetIpv4AddressRows();
                var liveKeys = new HashSet<string>(StringComparer.Ordinal);
                foreach (var row in liveRows)
                {
                    AddRowObjects(row);
                    liveKeys.Add(BuildKey(row.IfIndex, row.Address));
                }

                foreach (var row in _customRows.Values
                    .Where(row => !liveKeys.Contains(BuildKey(row.IfIndex, row.Address)))
                    .OrderBy(row => row.IfIndex)
                    .ThenBy(row => row.Address.ToString(), StringComparer.Ordinal))
                {
                    AddRowObjects(row);
                }
            }
        }

        public bool TryCreateForSet(Variable variable)
        {
            if (!TryParseRowKey(variable.Id, out var ifIndex, out var address))
            {
                return false;
            }

            lock (_syncRoot)
            {
                var key = BuildKey(ifIndex, address);
                if (!_customRows.ContainsKey(key) && !MibHelper.GetIpv4AddressRows().Any(row => row.IfIndex == ifIndex && row.Address.Equals(address)))
                {
                    _customRows[key] = new IpNetToMediaCustomRow
                    {
                        IfIndex = ifIndex,
                        Address = address,
                        PhysicalAddress = Array.Empty<byte>(),
                        Type = 3,
                    };
                }

                _elements.Clear();
                LoadElements();
                return true;
            }
        }

        private void AddRowObjects(MibHelper.Ipv4AddressRow row)
        {
            _elements.Add(new ipNetToMediaIfIndex(row.Interface, row.IfIndex.ToString(), row.Address.ToString()));
            _elements.Add(new ipNetToMediaPhysAddress(row.Interface, row.IfIndex.ToString(), row.Address.ToString()));
            _elements.Add(new ipNetToMediaNetAddress(row.Interface, row.IfIndex.ToString(), row.Address.ToString()));
            _elements.Add(new ipNetToMediaType(row.Interface, row.IfIndex.ToString(), row.Address.ToString()));
        }

        private void AddRowObjects(IpNetToMediaCustomRow row)
        {
            _elements.Add(new ipNetToMediaIfIndex(row));
            _elements.Add(new ipNetToMediaPhysAddress(row));
            _elements.Add(new ipNetToMediaNetAddress(row));
            _elements.Add(new ipNetToMediaType(row));
        }

        private static bool TryParseRowKey(ObjectIdentifier id, out int ifIndex, out IPAddress address)
        {
            ifIndex = 0;
            address = IPAddress.Any;

            var parts = id.ToString().Split('.');
            if (parts.Length != 15)
            {
                return false;
            }

            if (!parts[0].Equals("1", StringComparison.Ordinal) ||
                !parts[1].Equals("3", StringComparison.Ordinal) ||
                !parts[2].Equals("6", StringComparison.Ordinal) ||
                !parts[3].Equals("1", StringComparison.Ordinal) ||
                !parts[4].Equals("2", StringComparison.Ordinal) ||
                !parts[5].Equals("1", StringComparison.Ordinal) ||
                !parts[6].Equals("4", StringComparison.Ordinal) ||
                !parts[7].Equals("22", StringComparison.Ordinal) ||
                !parts[8].Equals("1", StringComparison.Ordinal))
            {
                return false;
            }

            if (!int.TryParse(parts[9], out var column) || column < 1 || column > 4)
            {
                return false;
            }

            if (!int.TryParse(parts[10], out ifIndex) || ifIndex <= 0)
            {
                return false;
            }

            if (!TryParseIpv4Address(parts[11], parts[12], parts[13], parts[14], out address))
            {
                return false;
            }

            return true;
        }

        private static bool TryParseIpv4Address(string p1, string p2, string p3, string p4, out IPAddress address)
        {
            address = IPAddress.Any;
            if (!byte.TryParse(p1, out var b1) ||
                !byte.TryParse(p2, out var b2) ||
                !byte.TryParse(p3, out var b3) ||
                !byte.TryParse(p4, out var b4))
            {
                return false;
            }

            address = new IPAddress([b1, b2, b3, b4]);
            return true;
        }

        private static string BuildKey(int ifIndex, IPAddress address)
        {
            return $"{ifIndex}:{address}";
        }
    }
}
