// Initially generated by MibCustomFileGenerator
// IMPORTANT: This file can be modified, but won't be updated by the generator again once created.
// Original file name is /Users/lextm/sharpmibsuite/sharpsnmplib-samples/Samples/snmpd/Mibs/IF-MIB.txt
using System;
using System.Collections.Generic;
using Lextm.SharpSnmpLib;
using Samples.Pipeline;
using System.Linq;
using System.Net.NetworkInformation;
using SnmpD;
// using Lextm.SharpSnmpPro.Mib; // TODO: Uncomment if syntax validation is required.

namespace IF_MIB
{

    partial class ifNumber
    {
        void OnCreate()
        {
        }

        public override ISnmpData Data
        {
            get { return new Integer32(MibHelper.GetInterfaceRows().Count); }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifTableLastChange
    {
        private ISnmpData _data = new TimeTicks(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifTable
    {
        void OnCreate()
        {
            NetworkChange.NetworkAddressChanged +=
                (sender, args) => LoadElements();

            NetworkChange.NetworkAvailabilityChanged +=
                (sender, args) => LoadElements();

            LoadElements();
        }

        private void LoadElements()
        {
            _elements.Clear();
            foreach (var row in MibHelper.GetInterfaceRows())
            {
                _elements.Add(new ifIndex(row));
                _elements.Add(new ifDescr(row));
                _elements.Add(new ifType(row));
                _elements.Add(new ifMtu(row));
                _elements.Add(new ifSpeed(row));
                _elements.Add(new ifPhysAddress(row));
                _elements.Add(new ifAdminStatus(row));
                _elements.Add(new ifOperStatus(row));
                _elements.Add(new ifLastChange(row));
                _elements.Add(new ifInOctets(row));
                _elements.Add(new ifInUcastPkts(row));
                _elements.Add(new ifInNUcastPkts(row));
                _elements.Add(new ifInDiscards(row));
                _elements.Add(new ifInErrors(row));
                _elements.Add(new ifInUnknownProtos(row));
                _elements.Add(new ifOutOctets(row));
                _elements.Add(new ifOutUcastPkts(row));
                _elements.Add(new ifOutNUcastPkts(row));
                _elements.Add(new ifOutDiscards(row));
                _elements.Add(new ifOutErrors(row));
                _elements.Add(new ifOutQLen(row));
                _elements.Add(new ifSpecific(row));
            }
        }
    }

    partial class ifIndex
    {
        public ifIndex(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Integer32(row.IfIndex);
        }

        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifDescr
    {
        public ifDescr(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new OctetString(row.Description);
        }

        private ISnmpData _data = OctetString.Empty; // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifType
    {
        public ifType(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Integer32(row.TypeValue);
        }

        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifMtu
    {
        public ifMtu(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Integer32(row.Mtu);
        }

        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifSpeed
    {
        public ifSpeed(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Gauge32(row.Speed);
        }

        private ISnmpData _data = new Gauge32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifPhysAddress
    {
        public ifPhysAddress(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new OctetString(row.PhysicalAddress);
        }

        private ISnmpData _data = OctetString.Empty; // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifAdminStatus
    {
        public ifAdminStatus(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Integer32(row.AdminStatus);
        }

        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifAdminStatus", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifOperStatus
    {
        public ifOperStatus(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Integer32(row.OperStatus);
        }

        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifLastChange
    {
        public ifLastChange(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new TimeTicks(0);
        }

        private ISnmpData _data = new TimeTicks(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifInOctets
    {
        public ifInOctets(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.InOctets);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifInUcastPkts
    {
        public ifInUcastPkts(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.InUcastPackets);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifInNUcastPkts
    {
        public ifInNUcastPkts(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.InNonUcastPackets);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifInDiscards
    {
        public ifInDiscards(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.InDiscards);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifInErrors
    {
        public ifInErrors(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.InErrors);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifInUnknownProtos
    {
        public ifInUnknownProtos(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.InUnknownProtocols);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifOutOctets
    {
        public ifOutOctets(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.OutOctets);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifOutUcastPkts
    {
        public ifOutUcastPkts(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.OutUcastPackets);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifOutNUcastPkts
    {
        public ifOutNUcastPkts(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.OutNonUcastPackets);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifOutDiscards
    {
        public ifOutDiscards(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.OutDiscards);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifOutErrors
    {
        public ifOutErrors(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Counter32(row.OutErrors);
        }

        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifOutQLen
    {
        public ifOutQLen(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new Gauge32(row.OutQueueLength);
        }

        private ISnmpData _data = new Gauge32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifSpecific
    {
        public ifSpecific(MibHelper.InterfaceRow row)
            : this(row.Index)
        {
            _data = new ObjectIdentifier(row.SpecificOid);
        }

        private ISnmpData _data = new ObjectIdentifier(".0.0"); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifXTable
    {
        void OnCreate()
        {
            // TODO: Add table entries here
        }
    }

    partial class ifName
    {
        private ISnmpData _data = OctetString.Empty; // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifInMulticastPkts
    {
        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifInBroadcastPkts
    {
        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifOutMulticastPkts
    {
        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifOutBroadcastPkts
    {
        private ISnmpData _data = new Counter32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifHCInOctets
    {
        private ISnmpData _data = new Counter64(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifHCInUcastPkts
    {
        private ISnmpData _data = new Counter64(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifHCInMulticastPkts
    {
        private ISnmpData _data = new Counter64(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifHCInBroadcastPkts
    {
        private ISnmpData _data = new Counter64(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifHCOutOctets
    {
        private ISnmpData _data = new Counter64(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifHCOutUcastPkts
    {
        private ISnmpData _data = new Counter64(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifHCOutMulticastPkts
    {
        private ISnmpData _data = new Counter64(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifHCOutBroadcastPkts
    {
        private ISnmpData _data = new Counter64(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifLinkUpDownTrapEnable
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifLinkUpDownTrapEnable", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifHighSpeed
    {
        private ISnmpData _data = new Gauge32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifPromiscuousMode
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifPromiscuousMode", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifConnectorPresent
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifAlias
    {
        private ISnmpData _data = OctetString.Empty; // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifAlias", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifCounterDiscontinuityTime
    {
        private ISnmpData _data = new TimeTicks(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifStackTable
    {
        void OnCreate()
        {
            // TODO: Add table entries here
        }
    }

    partial class ifStackHigherLayer
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifStackHigherLayer", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifStackLowerLayer
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifStackLowerLayer", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifStackStatus
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifStackStatus", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifStackLastChange
    {
        private ISnmpData _data = new TimeTicks(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifRcvAddressTable
    {
        void OnCreate()
        {
            // TODO: Add table entries here
        }
    }

    partial class ifRcvAddressAddress
    {
        private ISnmpData _data = OctetString.Empty; // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifRcvAddressAddress", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifRcvAddressStatus
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifRcvAddressStatus", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifRcvAddressType
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifRcvAddressType", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifTestTable
    {
        void OnCreate()
        {
            // TODO: Add table entries here
        }
    }

    partial class ifTestId
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifTestId", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifTestStatus
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifTestStatus", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifTestType
    {
        private ISnmpData _data = new ObjectIdentifier(".0.0"); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifTestType", value) to validate data
            set { _data = value; }
        }
    }

    partial class ifTestResult
    {
        private ISnmpData _data = new Integer32(0); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifTestCode
    {
        private ISnmpData _data = new ObjectIdentifier(".0.0"); // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            set { if (CheckAccess) throw new AccessFailureException(); }
        }
    }

    partial class ifTestOwner
    {
        private ISnmpData _data = OctetString.Empty; // TODO: remove initial assignment if you want to do it in constructors.

        void OnCreate()
        {
            // TODO: initialization here
        }

        public override ISnmpData Data
        {
            get { return _data; }
            // TODO: Use ObjectRegistryBase.Verify("IF-MIB", "ifTestOwner", value) to validate data
            set { _data = value; }
        }
    }
}

namespace Lextm.SharpSnmpPro.Mib
{
    /// <summary>
    /// Registration class for IF-MIB MIB objects.
    /// </summary>
    public static partial class ModuleRegister
    {
        /// <summary>
        /// Registers all objects from this module to the specified object store.
        /// </summary>
        /// <param name="store">The object store to register objects with.</param>
        public static void RegisterIF_MIB(ObjectStore store)
        {
            if (store == null)
            {
                throw new ArgumentNullException(nameof(store));
            }

            store.Add(new IF_MIB.ifNumber());
            store.Add(new IF_MIB.ifTableLastChange());
            store.Add(new IF_MIB.ifTable());
            store.Add(new IF_MIB.ifXTable());
            store.Add(new IF_MIB.ifStackTable());
            store.Add(new IF_MIB.ifStackLastChange());
            store.Add(new IF_MIB.ifRcvAddressTable());
            store.Add(new IF_MIB.ifTestTable());
        }
    }
}
